[package]
name = "avr_test"
version = "0.1.0"
edition = '2021'

[dependencies]
avr-std-stub = { path = "avr-std-stub" }
avr_delay = { path = "delay" }
definitions = { path = "definitions" }

[profile.release]
lto = true
